#!/bin/sh

commit_msg_file="$1"

first_line="$(head -n 1 "$commit_msg_file")"

case "$first_line" in
  # bypass-check\ *)
  bypass-check:*)
    echo "⚠️  Pre-commit checks bypassed by commit message."
    exit 0
    ;;
esac

echo "Running pre-commit checks..."
echo

# Run Ruff
echo "> ruff check ."
ruff check .
if [ $? -ne 0 ]; then
    echo "✖ ruff check failed. Aborting commit."
    exit 1
else
    echo "✔ ruff check passed."
    echo
fi

# Run Mypy
echo "> mypy --install-types --non-interactive ."
mypy --install-types --non-interactive .
if [ $? -ne 0 ]; then
    echo "✖ mypy failed. Aborting commit."
    exit 1
else
    echo "✔ mypy passed."
    echo
fi

# Run Pyright
echo "> pyright"
pyright
if [ $? -ne 0 ]; then
    echo "✖ pyright failed. Aborting commit."
    exit 1
else
    echo "✔ pyright passed."
    echo
fi

echo "✔ All checks passed. Proceeding with commit."
